spring:
  application:
    name: HeartBeat
  batch.job.enabled: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:heartbeat
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
        trace: false